xiin:
  home:
    url: 'http://inxi.googlecode.com'

  modules:
    exclude   : '.svn'
    ext       : [ 'svn', 'yml' ]
    directory :
      url: '/svn/modules/trash80-experimental/modules/xiin'
    text:
      url:
        list  : '{0}{1}'
        full  : '{0}{1}/{2}'
        module: '{0}/{1}'

  report:
    elipse: '...'
    status:
      beginUpdate   : 'Please wait while xiin checks for updates...'
      updating      : 'Updating {0}'
      upToDate      : 'Nothing to update.'
      continue      : 'Continuing...'
      checkingRemote: 'Checking latest versions of xiin modules...'
      checkingLocal : 'Checking local xiin module version...'

    error: []
